apiVersion: v1
kind: Pod
metadata:
  name: myweb-pod1
  labels:
    env: testing
    region: IN
spec:
  containers:
  - name: myweb-con
    image: arnab83/php-webserver-centos7:latest
    volumeMounts:
      - name: web-vol1
        mountPath: /var/www/html
  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName: web-pvc
